ar_layers: &id001 []
compute_components_flag: false
config_ar: !!python/object:neuralprophet.configure.AR
  ar_layers: *id001
  ar_reg: null
  n_lags: 48
  reg_lambda: null
config_events: null
config_holidays: null
config_lagged_regressors: null
config_normalization: !!python/object:neuralprophet.configure.Normalization
  global_data_params: !!python/object/apply:collections.OrderedDict
  - - - ds
      - &id003 !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
        - 959
        - 10
        shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
        - 0
        - null
        - null
        - 10
    - - y
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - &id002 !!python/object/apply:numpy.dtype
          args:
          - f8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - !!binary |
          RI+pWQrv6z8=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          AAAAAAAAAAA=
    - - rsi
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          IhOOp6R/6D8=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          AAAAAAAAAAA=
    - - ema
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          lJolbsSj7D8=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          AAAAAAAAAAA=
    - - adx
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          RvYQbzYB5j8=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          AAAAAAAAAAA=
    - - atr
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          3BKy5W1+6T8=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          AAAAAAAAAAA=
    - - volume
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          CCmNZPyzxj8=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          AAAAAAAAAAA=
    - - cci
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          waie7jcx4z8=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          AAAAAAAAAAA=
    - - williams_r
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          JlheOhET7j8=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          AAAAAAAAAAA=
    - - momentum
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          TgHbIoMG5D8=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          AAAAAAAAAAA=
    - - mfi
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          WdO9d3Lp6z8=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          AAAAAAAAAAA=
    - - mass_index
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          6dIlWN9r7D8=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          AAAAAAAAAAA=
    - - fib_23_6
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          uGVOlyW9zkA=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          HNMTlkwn9EA=
    - - fib_38_2
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          iDO/mnNLz0A=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          kZvhBrjs80A=
    - - fib_50
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          oHA9Cne+z0A=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          UrgehV+980A=
    - - fib_61_8
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          4NbdPL0Y0EA=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          E9VbAweO80A=
    - - fib_78_6
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          5Ii1+Jxq0EA=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          Tdu/sp5K80A=
  global_normalization: true
  global_time_normalization: true
  local_data_params: !!python/object/apply:collections.OrderedDict
  - - - __df__
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - *id003
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                RI+pWQrv6z8=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                AAAAAAAAAAA=
          - - rsi
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                IhOOp6R/6D8=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                AAAAAAAAAAA=
          - - ema
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                lJolbsSj7D8=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                AAAAAAAAAAA=
          - - adx
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                RvYQbzYB5j8=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                AAAAAAAAAAA=
          - - atr
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                3BKy5W1+6T8=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                AAAAAAAAAAA=
          - - volume
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                CCmNZPyzxj8=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                AAAAAAAAAAA=
          - - cci
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                waie7jcx4z8=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                AAAAAAAAAAA=
          - - williams_r
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                JlheOhET7j8=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                AAAAAAAAAAA=
          - - momentum
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                TgHbIoMG5D8=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                AAAAAAAAAAA=
          - - mfi
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                WdO9d3Lp6z8=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                AAAAAAAAAAA=
          - - mass_index
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                6dIlWN9r7D8=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                AAAAAAAAAAA=
          - - fib_23_6
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                uGVOlyW9zkA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                HNMTlkwn9EA=
          - - fib_38_2
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                iDO/mnNLz0A=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                kZvhBrjs80A=
          - - fib_50
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                oHA9Cne+z0A=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                UrgehV+980A=
          - - fib_61_8
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                4NbdPL0Y0EA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                E9VbAweO80A=
          - - fib_78_6
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                5Ii1+Jxq0EA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                Tdu/sp5K80A=
  normalize: auto
  unknown_data_normalization: false
config_regressors: !!python/object:neuralprophet.configure.ConfigFutureRegressors
  d_hidden: 4
  model: linear
  num_hidden_layers: 2
  regressors: !!python/object/apply:collections.OrderedDict
  - - - rsi
      - !!python/object:neuralprophet.configure.Regressor
        mode: additive
        normalize: auto
        reg_lambda: null
    - - ema
      - !!python/object:neuralprophet.configure.Regressor
        mode: additive
        normalize: auto
        reg_lambda: null
    - - adx
      - !!python/object:neuralprophet.configure.Regressor
        mode: additive
        normalize: auto
        reg_lambda: null
    - - atr
      - !!python/object:neuralprophet.configure.Regressor
        mode: additive
        normalize: auto
        reg_lambda: null
    - - volume
      - !!python/object:neuralprophet.configure.Regressor
        mode: additive
        normalize: auto
        reg_lambda: null
    - - cci
      - !!python/object:neuralprophet.configure.Regressor
        mode: additive
        normalize: auto
        reg_lambda: null
    - - williams_r
      - !!python/object:neuralprophet.configure.Regressor
        mode: additive
        normalize: auto
        reg_lambda: null
    - - momentum
      - !!python/object:neuralprophet.configure.Regressor
        mode: additive
        normalize: auto
        reg_lambda: null
    - - mfi
      - !!python/object:neuralprophet.configure.Regressor
        mode: additive
        normalize: auto
        reg_lambda: null
    - - mass_index
      - !!python/object:neuralprophet.configure.Regressor
        mode: additive
        normalize: auto
        reg_lambda: null
    - - fib_23_6
      - !!python/object:neuralprophet.configure.Regressor
        mode: additive
        normalize: auto
        reg_lambda: null
    - - fib_38_2
      - !!python/object:neuralprophet.configure.Regressor
        mode: additive
        normalize: auto
        reg_lambda: null
    - - fib_50
      - !!python/object:neuralprophet.configure.Regressor
        mode: additive
        normalize: auto
        reg_lambda: null
    - - fib_61_8
      - !!python/object:neuralprophet.configure.Regressor
        mode: additive
        normalize: auto
        reg_lambda: null
    - - fib_78_6
      - !!python/object:neuralprophet.configure.Regressor
        mode: additive
        normalize: auto
        reg_lambda: null
config_seasonality: !!python/object:neuralprophet.configure.ConfigSeasonality
  computation: fourier
  condition_name: null
  daily_arg: true
  daily_global_local: auto
  global_local: global
  mode: additive
  periods: !!python/object/apply:collections.OrderedDict
  - - - weekly
      - !!python/object:neuralprophet.configure.Season
        arg: true
        condition_name: null
        global_local: global
        period: 7
        resolution: 3
    - - daily
      - !!python/object:neuralprophet.configure.Season
        arg: true
        condition_name: null
        global_local: global
        period: 1
        resolution: 6
  reg_lambda: 0
  seasonality_local_reg: false
  weekly_arg: true
  weekly_global_local: auto
  yearly_arg: false
  yearly_global_local: auto
config_train: !!python/object:neuralprophet.configure.Train
  batch_size: 64
  epochs: 150
  lambda_delay: 75
  learning_rate: 0.003
  loss_func: !!python/object:torch.nn.modules.loss.SmoothL1Loss
    _backward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _buffers: !!python/object/apply:collections.OrderedDict
    - []
    _forward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
    - []
    _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
    - []
    _is_full_backward_hook: null
    _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _modules: !!python/object/apply:collections.OrderedDict
    - []
    _non_persistent_buffers_set: !!set {}
    _parameters: !!python/object/apply:collections.OrderedDict
    - []
    _state_dict_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    beta: 0.3
    reduction: none
    training: true
  loss_func_name: SmoothL1Loss
  lr_finder_args: {}
  n_data: 912
  newer_samples_start: 0.0
  newer_samples_weight: 2
  optimizer: !!python/name:torch.optim.adamw.AdamW ''
  optimizer_args:
    weight_decay: 0.001
  quantiles:
  - 0.5
  reg_delay_pct: 0.5
  reg_lambda_trend: null
  scheduler: !!python/name:torch.optim.lr_scheduler.OneCycleLR ''
  scheduler_args:
    anneal_strategy: cos
    div_factor: 10.0
    final_div_factor: 10.0
    pct_start: 0.3
    three_phase: true
  trend_reg_threshold: null
config_trend: !!python/object:neuralprophet.configure.Trend
  changepoints: null
  changepoints_range: 0.8
  growth: linear
  n_changepoints: 10
  trend_global_local: global
  trend_local_reg: false
  trend_reg: 0
  trend_reg_threshold: null
id_list:
- __df__
lagged_reg_layers: []
max_lags: 48
meta_used_in_model: false
metrics:
  MAE:
  - MeanAbsoluteError
  - {}
  RMSE:
  - MeanSquaredError
  - squared: false
n_forecasts: 1
n_lags: 48
num_seasonalities_modelled: 1
num_seasonalities_modelled_dict: !!python/object/apply:collections.OrderedDict
- - - yearly
    - 1
  - - weekly
    - 1
  - - daily
    - 1
num_trends_modelled: 1
